---
- name: "CERTIFICATE : LEXICON DNS-01"
  block:
    - name: "CERTIFICATE {{ le_certificate_loop.domain }} : LEXICON DNS-01 - ensure username is defined"
      fail:
        msg: "Unable to get {{ le_certificate_loop_dns_provider }} username from certificate variable 'auth_username'
              or default variable 'le_dns_lexicon_auth_username'!"
      when: (le_certificate_loop.auth_username| default(le_dns_lexicon_auth_username, True)| default('', True)) == ""

    - name: "CERTIFICATE {{ le_certificate_loop.domain }} : LEXICON DNS-01 - ensure password/token is defined"
      fail:
        msg: "Unable to get {{ le_certificate_loop_dns_provider|upper }} token or password from certificate
              variables 'auth_token'/ 'auth_password' or default variable 'le_dns_lexicon_auth_token'/
              'le_dns_lexicon_auth_password'!"
      when:
        - (le_certificate_loop.auth_token| default(le_dns_lexicon_auth_token, True)| default('', True)) == ""
        - (le_certificate_loop.auth_password| default(le_dns_lexicon_auth_password, True)| default('', True)) == ""

    - name: "CERTIFICATE {{ le_certificate_loop.domain }} : LEXICON DNS-01 - sign/renew certificate"
      shell: >
        PROVIDER={{ le_certificate_loop_dns_provider }}
        {{ (le_certificate_loop.option_envs| default(le_dns_lexicon_option_envs))| join(' ') }}
        LEXICON_{{ le_certificate_loop_dns_provider|upper }}_AUTH_USERNAME='{{ le_certificate_loop.auth_username|
        default(le_dns_lexicon_auth_username, True) }}'
        LEXICON_{{ le_certificate_loop_dns_provider|upper }}_AUTH_TOKEN='{{ le_certificate_loop.auth_token|
        default(le_dns_lexicon_auth_token, True)| default('', True) }}'
        LEXICON_{{ le_certificate_loop_dns_provider|upper }}_AUTH_PASSWORD='{{ le_certificate_loop.auth_password|
        default(le_dns_lexicon_auth_password, True)| default('', True) }}'
        /opt/letsencrypt/dehydrated/dehydrated -c
        -d '{{ le_certificate_loop.domain }} {{ le_certificate_loop.altnames| default('') }}'
        -t 'dns-01' -k '{{ le_dehydrated_hooks_dir }}/lexicon/{{ le_dns_lexicon_hook_file }}'
      async: 1500
      poll: 15
      no_log: yes
  tags:
    - always
